---
project:
  type: website

format:
  html:
    include-in-header: goatcounter.html
    theme: cyborg

website:
  favicon: favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/blog
  site-url: https://paddyroddy.github.io/blog
  title: Patrick J. Roddy
