---
project:
  type: website

format:
  html:
    theme: cyborg

website:
  body-footer:
    <script async
    data-goatcounter="https://paddyroddy-blog.goatcounter.com/count"
    src="//gc.zgo.at/count.js"></script>
  favicon: favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/blog
  site-url: https://paddyroddy.github.io/blog
  title: Patrick J. Roddy
